name: Report an Issue
description: Anything in existing documentation that is wrong, missing, or misleading.
labels: ["error/wrong-info", "error/misleading"]
body:
  - type: markdown
    attributes:
      value: |
        If you want to contribute a quick fix yourself, you don't need to write an issue. See [Submit a Docs PR](https://www.notion.so/astronomerio/Submit-a-Docs-PR-a3ca9018fdbc4206b120a6d530a8401b).
  - type: dropdown
    id: issuetype
    attributes:
      label: Issue Type
      multiple: true
      options:
        - Inaccurate or out-of-date
        - Missing or misleading
        - Typo or broken link
        - Issue with Docs website
    validations:
      required: true
  - type: textarea
    id: doc
    attributes:
      label: Links to Affected Docs
      description: Share a link to the document(s) where the issue exists.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: The Issue
      description: Describe what exactly is wrong. Be as descriptive as possible.
      placeholder:  
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: The Fix
      description: Describe what needs to be added, updated, or otherwise changed to address the issue.
      placeholder:  
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add any related Slack threads, Zendesk tickets, or other information that the docs team can use to resolve the issue.

  
