name: Report an issue in documentation
description: Any request related to existing documentation that has an issue
assignees:
  - jwitz
body:
  - type: markdown
    attributes:
      value: |
        To submit a quick fix yourself, see [Submit a docs PR](https://www.notion.so/astronomerio/Submit-a-Docs-PR-a3ca9018fdbc4206b120a6d530a8401b).
  - type: dropdown
    id: issuetype
    attributes:
      label: Issue type
      multiple: true
      options:
        - Inaccurate content
        - Missing context
        - Typo
        - Bug/ broken link
    validations:
      required: true
  - type: input
    id: doc
    attributes:
      label: Affected docs
      description: Share a link to the document(s) where the issue exists.
      placeholder: For example, 'https://docs.astronomer.io/astro/develop-project', 'All CLI docs', 'Release notes'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the issue and the fix
      description: Describe the issue and how it should be fixed.
      placeholder:  Be as descriptive as possible. If there is existing documentation or related issues, link to them here. If you're not sot sure how best to proceed with your request, contact the docs team.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Add additional information here that can help the docs team resolve the issue.

  
