name: Request new documentation 
description: A new doc or topic on an existing Astro feature or behavior
assignees:
  - jwitz
  - kwcanuck
labels: ["new-feature"]
body:
  - type: dropdown
    id: impact
    attributes:
      label: Request type
      multiple: true
      options:
        - Setup steps for an existing feature or supported configuration
        - Best practices or recommendations
        - Technical overview or reference
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the documentation request
    validations:
      required: true
  - type: textarea
    id: relateddocs
    attributes:
      label: Links to related documentation
  - type: textarea
    id: reviewers
    attributes:
      label: Due date
      placeholder: For example, 'Q2 2023', '2/12/2023', 'Within the next month'
  - type: input
    id: deadline
    attributes:
      label: Required reviewers
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description:  Share any internal or external docs that provide context for the feature. Productboard tickets, GitHub issues, Slack messages are all welcome and encouraged!

  
