name: Request documentation for an upcoming product change
description: Request new or updated documentation for an existing Astro or Astronomer Software feature.
assignees:
  - jwitz
  - kwcanuck
labels: ["kind/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Want to document the new feature yourself? Use the [new feature documentation template](https://github.com/astronomer/docs/blob/main/new-feature-template.md).
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: New feature description
      description: Why is the new feature or functionality significant? What benefit does it provide? Why should customers care about this feature or functionality?
    validations:
      required: true
  - type: input
    id: reviewer
    attributes:
      label: Required reviewers
    validations:
      required: true
  - type: textarea
    id: relateddocs
    attributes:
      label: Notion/ GitHub/ ProductBoard links
  - type: textarea
    id: deadline
    attributes:
      label: Release date
      placeholder: For example, 'Q2 2023', '2/12/2023', 'Within the next month'
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Add additional information here that can help the docs team understand the requirements.

  
