name: Docs Freshness
on: workflow_dispatch

jobs:
  exportmetrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
          git checkout main
    - name: Install ack
      run: sudo apt-get install ack
    - name: Run build script
      run: ./lastUpdated.sh
      shell: bash
    - uses: jakejarvis/s3-sync-action@master
      name: Sync to S3
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2' 
        SOURCE_DIR: '.github/metrics'
