name: Reindex Algolia
on:
  push
    # branches:
    #   - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper-base
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Algolia
        run: "pipenv run python -m src.index"
